trigger:
  - main

pr:
  - main

jobs:
  - job: "Build"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'clean build'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        sonarQubeRunAnalysis: false
    - task: CopyFiles@2
      displayName: "Copy build output to artifact directory"
      inputs:
        SourceFolder: 'build/libs'
        Contents: '*.jar'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: CopyFiles@2
      displayName: "Copy docker and helm files"
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: |
          Dockerfile
          .dockerignore
          entrypoint.sh
        TargetFolder: '$(Build.ArtifactStagingDirectory)/'
        OverWrite: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
  - job: "DockerHub"
    dependsOn: "Build"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
        checkDownloadedFiles: true
    - task: PowerShell@2
      displayName: 'Copy Specific Config'
      inputs:
        targetType: inline
        script: Copy-Item -Path "$(System.ArtifactsDirectory)/s-1.0.0.jar" -Destination "$(build.ArtifactsDirectory)/app.jar"
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'mellon.configserver'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest