name: Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:    
    - uses: actions/checkout@v2
        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
 
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Execute Gradle build
      run: ./gradlew build

    - name: Create folder
      run: |
        mkdir -p app
        
    - name: Copy Jar      
      uses: canastro/copy-action@0.0.2
      with:
        source: ./build/libs/Mellon.ConfigServer-1.0.0.jar        
        target: ./app/app.jar
    
    - name: Copy Entrypoint      
      uses: canastro/copy-action@0.0.2
      with:
        source: ./entrypoint.sh        
        target: ./app/entrypoint.sh

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1.12.0
      with:
        username: 1berto
        password: 9aadda7b-4cbf-43aa-ac16-68ff787c3145
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: |
          1berto/mellon.configserver:latest
          1berto/mellon.configserver:${{github.run_number}}
