name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - name: Test
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        echo $DOCKERHUB_USERNAME
        echo $DOCKERHUB_TOKEN
    
    - uses: actions/checkout@v2
    
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
 
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Execute Gradle build
      run: ./gradlew build

    - name: Create folder
      run: |
        mkdir -p app
        
    - name: Copy Jar      
      uses: canastro/copy-action@0.0.2
      with:
        # Source file
        source: ./build/libs/Mellon.ConfigServer-1.0.0.jar
        # Target file
        target: ./app/app.jar
    
    - name: Copy Entrypoint      
      uses: canastro/copy-action@0.0.2
      with:
        # Source file
        source: ./entrypoint.sh
        # Target file
        target: ./app/entrypoint.sh

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: |
          1berto/mellon.configserver:latest
          1berto/mellon.configserver:${{github.run_number}}
